import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Locator, type Page } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
import path from 'node:path'

const evidenceDir = process.env.PROOFCANVAS_EVIDENCE_DIR ?? path.join(process.cwd(), '.proofcanvas-evidence')

async function dragBy(page: Page, locator: Locator, dx: number, dy: number, startXOffset?: number) {
  await locator.scrollIntoViewIfNeeded()
  const box = await locator.boundingBox()
  expect(box, `Expected a visible box for ${await locator.getAttribute('aria-label')}`).not.toBeNull()
  const relativeX = startXOffset === undefined ? box!.width / 2 : Math.min(box!.width - 1, Math.max(1, startXOffset))
  const relativeY = box!.height / 2
  await locator.hover({ position: { x: relativeX, y: relativeY } })
  const settledBox = await locator.boundingBox()
  expect(settledBox).not.toBeNull()
  const x = settledBox!.x + relativeX
  const y = settledBox!.y + relativeY
  await page.mouse.down()
  await page.mouse.move(x + dx, y + dy, { steps: 5 })
  await page.mouse.up()
}

async function historyCount(page: Page) {
  return Number(await page.getByRole('application', { name: 'ProofCanvas editor' }).getAttribute('data-history-past-count'))
}

async function boxCenter(locator: Locator) {
  const box = await locator.boundingBox()
  expect(box, `Expected a visible box for ${await locator.getAttribute('aria-label')}`).not.toBeNull()
  return { x: box!.x + box!.width / 2, y: box!.y + box!.height / 2 }
}

async function setSelectedPosition(page: Page, x: number, y: number) {
  const xPosition = page.getByRole('spinbutton', { name: 'X position' })
  await xPosition.fill(String(x))
  await xPosition.blur()
  await expect(xPosition).toHaveValue(String(x))
  const yPosition = page.getByRole('spinbutton', { name: 'Y position' })
  await yPosition.fill(String(y))
  await yPosition.blur()
  await expect(yPosition).toHaveValue(String(y))
}

test('complete structured edit-to-Manim journey', async ({ page }, testInfo) => {
  const ownerPassword = process.env.PROOFCANVAS_E2E_OWNER_PASSWORD
  expect(ownerPassword, 'The isolated acceptance harness must provide an ephemeral owner password').toBeTruthy()
  const consoleErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('pageerror', (error) => consoleErrors.push(error.message))

  const compatibility = await page.request.get('/proofcanvas', { maxRedirects: 0 })
  expect(compatibility.status()).toBe(307)
  expect(compatibility.headers().location).toBe('/login')

  await page.goto('/')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Owner password').fill(ownerPassword!)
  await page.getByRole('button', { name: 'Log in' }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('heading', { name: 'Your mathematical motion projects' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Project title' }).fill('M3.7c semantic component acceptance')
  await page.getByRole('button', { name: 'New sample project' }).click()
  await expect(page).toHaveURL(/\/projects\/project-[a-f0-9]{24}$/)
  const editor = page.getByRole('application', { name: 'ProofCanvas editor' })
  await expect(editor).toHaveAttribute('data-project-id', /^project-[a-f0-9]{24}$/)
  await expect(editor).toHaveAttribute('data-durable', 'true')
  const projectId = await editor.getAttribute('data-project-id')
  expect(projectId).not.toBeNull()
  const authenticatedCompatibility = await page.request.get('/proofcanvas', { maxRedirects: 0 })
  expect(authenticatedCompatibility.status()).toBe(307)
  expect(authenticatedCompatibility.headers().location).toBe('/')
  await expect(page.getByRole('tree', { name: 'Objects' })).toBeVisible()
  await expect(page.locator('[role="tabpanel"][aria-label="Animation timeline"]')).toBeVisible()

  const playhead = page.getByRole('slider', { name: 'Sequence time' })
  await playhead.fill('12.5')
  await expect(page.getByRole('region', { name: 'Scene canvas' })).toHaveAttribute('data-preview-time', '12.5')
  await expect(page.locator('[data-object-id="object-equation-length"]')).toHaveCount(0)
  await expect(page.locator('[data-object-id="object-interval-third-1-left"]')).toBeVisible()
  await playhead.fill('15.2')
  await expect(page.locator('[data-object-id="object-equation-length"]')).toBeVisible()
  await playhead.fill('12.5')

  const title = page.locator('[data-object-id="object-title"]')
  await expect(title).toBeVisible()
  const editorialTransform = await title.getAttribute('transform')
  await playhead.fill('0.6')
  const editorialOpacity = Number(await title.getAttribute('opacity'))
  const titleText = title.locator('.pc-canvas-text')
  const editorialFontFamily = await titleText.evaluate((element) => getComputedStyle(element).fontFamily)
  const editorialBackground = await page.locator('.pc-stage-wrap').evaluate((element) => getComputedStyle(element).backgroundColor)
  const styleHistory = await historyCount(page)
  await page.getByRole('radio', { name: 'Raw Manim' }).check()
  await expect(page.getByRole('region', { name: 'Scene canvas' })).toHaveAttribute('data-preview-style-id', 'style-raw-manim')
  expect(await historyCount(page)).toBe(styleHistory + 1)
  expect(Number(await title.getAttribute('opacity'))).toBeCloseTo(editorialOpacity, 8)
  expect(await titleText.evaluate((element) => getComputedStyle(element).fontFamily)).not.toBe(editorialFontFamily)
  expect(await page.locator('.pc-stage-wrap').evaluate((element) => getComputedStyle(element).backgroundColor)).not.toBe(editorialBackground)
  await playhead.fill('12.5')
  expect(await title.getAttribute('transform')).toBe(editorialTransform)
  await title.click()
  const rawTitleBefore = await boxCenter(title)
  await dragBy(page, title, 100, 0)
  const rawTitleAfter = await boxCenter(title)
  expect(rawTitleAfter.x - rawTitleBefore.x).toBeGreaterThan(95)
  expect(rawTitleAfter.x - rawTitleBefore.x).toBeLessThan(105)
  expect(Math.abs(rawTitleAfter.y - rawTitleBefore.y)).toBeLessThan(2)
  await page.getByRole('button', { name: 'Undo' }).click()
  const rawTitleUndone = await boxCenter(title)
  expect(Math.abs(rawTitleUndone.x - rawTitleBefore.x)).toBeLessThan(2)
  await page.getByRole('radio', { name: 'Editorial Ink' }).check()
  expect(await historyCount(page)).toBe(styleHistory + 2)

  const screenshotName = testInfo.project.name.includes('1440')
    ? 'proofcanvas-editorial-1440x900.png'
    : 'proofcanvas-editorial-1280x800.png'

  const stageBounds = await page.locator('.pc-stage').boundingBox()
  const titleBounds = await title.boundingBox()
  expect(stageBounds).not.toBeNull()
  expect(titleBounds).not.toBeNull()
  expect(titleBounds!.x).toBeGreaterThanOrEqual(stageBounds!.x - 1)
  expect(titleBounds!.y).toBeGreaterThanOrEqual(stageBounds!.y - 1)
  expect(titleBounds!.x + titleBounds!.width).toBeLessThanOrEqual(stageBounds!.x + stageBounds!.width + 1)
  const captionBounds = await page.locator('.pc-stage-caption').boundingBox()
  const statusBounds = await page.getByRole('status', { name: 'Editor status', exact: true }).boundingBox()
  expect(captionBounds).not.toBeNull()
  expect(statusBounds).not.toBeNull()
  expect(captionBounds!.y + captionBounds!.height).toBeLessThanOrEqual(statusBounds!.y)

  const layout = await page.evaluate(() => ({
    innerWidth,
    innerHeight,
    documentWidth: document.documentElement.scrollWidth,
    documentHeight: document.documentElement.scrollHeight,
    canvasWidth: document.querySelector('[data-pc-canvas]')?.getBoundingClientRect().width ?? 0,
  }))
  expect(layout.documentWidth).toBeLessThanOrEqual(layout.innerWidth)
  expect(layout.documentHeight).toBeLessThanOrEqual(layout.innerHeight)
  expect(layout.canvasWidth).toBeGreaterThan(650)

  const axe = await new AxeBuilder({ page }).setLegacyMode(true).analyze()
  const materialA11y = axe.violations.filter(({ impact }) => impact === 'critical' || impact === 'serious')
  expect(materialA11y, JSON.stringify(materialA11y, null, 2)).toEqual([])

  const constructionTab = page.getByRole('tab', { name: /^Shot \d+, The construction,/ })
  const paradoxTab = page.getByRole('tab', { name: /^Shot \d+, The paradox,/ })
  await constructionTab.focus()
  await page.keyboard.press('ArrowRight')
  await expect(paradoxTab).toBeFocused()
  await expect(editor).toHaveAttribute('data-active-shot-id', 'shot-cantor-conclusion')
  await page.keyboard.press('ArrowLeft')
  await expect(constructionTab).toBeFocused()
  await expect(editor).toHaveAttribute('data-active-shot-id', 'shot-cantor-construction')
  await playhead.fill('12.5')

  const initialTitleLayer = page.getByRole('treeitem', { name: /Uncountable, Yet Zero Length/ })
  const initialSubtitleLayer = page.getByRole('treeitem', { name: /A quiet paradox/ })
  await initialTitleLayer.focus()
  await page.keyboard.press('ArrowDown')
  await expect(initialSubtitleLayer).toBeFocused()
  await expect(initialSubtitleLayer).toHaveAttribute('aria-selected', 'true')
  expect(await title.getAttribute('transform')).toBe(editorialTransform)
  await initialTitleLayer.click()
  if (testInfo.project.name === 'proofcanvas-chromium-1280') {
    const inspector = page.getByRole('form', { name: 'Object inspector', exact: true })
    const inspectorBounds = await inspector.boundingBox()
    expect(inspectorBounds).not.toBeNull()
    expect(inspectorBounds!.x).toBeGreaterThanOrEqual(0)
    expect(inspectorBounds!.x + inspectorBounds!.width).toBeLessThanOrEqual(1280)
    expect(inspectorBounds!.y + inspectorBounds!.height).toBeLessThanOrEqual(800)
    for (const name of ['Ungroup selection', 'Send to back']) {
      const control = page.getByRole('button', { name })
      const textFits = await control.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)
      expect(textFits, `${name} must not clip at 1280 px`).toBe(true)
    }
    for (const label of ['X position', 'Y position', 'Width', 'Height', 'Rotation']) {
      const bounds = await page.getByRole('spinbutton', { name: label, exact: true }).boundingBox()
      expect(bounds, `${label} must remain visible inside the 1280 px inspector`).not.toBeNull()
      expect(bounds!.x).toBeGreaterThanOrEqual(inspectorBounds!.x)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(inspectorBounds!.x + inspectorBounds!.width)
      expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(800)
    }
  }
  let before = await historyCount(page)
  const editorialTitleBefore = await boxCenter(title)
  await dragBy(page, title, 32, 18)
  expect(await historyCount(page)).toBe(before + 1)
  const editorialTitleAfter = await boxCenter(title)
  expect(Math.abs((editorialTitleAfter.x - editorialTitleBefore.x) - 32)).toBeLessThan(2)
  expect(Math.abs((editorialTitleAfter.y - editorialTitleBefore.y) - 18)).toBeLessThan(2)
  before = await historyCount(page)
  const resizeHandle = page.getByLabel(/^Resize selected object;/)
  const resizeBefore = await boxCenter(resizeHandle)
  await dragBy(page, resizeHandle, 22, 14)
  expect(await historyCount(page)).toBe(before + 1)
  const resizeAfter = await boxCenter(resizeHandle)
  expect(Math.abs((resizeAfter.x - resizeBefore.x) - 22)).toBeLessThan(2)
  expect(Math.abs((resizeAfter.y - resizeBefore.y) - 14)).toBeLessThan(2)
  before = await historyCount(page)
  const rotateHandle = page.getByLabel(/^Rotate selected object;/)
  const rotateBefore = await boxCenter(rotateHandle)
  const rotationBefore = await page.getByRole('spinbutton', { name: 'Rotation' }).inputValue()
  await dragBy(page, rotateHandle, 25, -8)
  expect(await historyCount(page)).toBe(before + 1)
  expect(await page.getByRole('spinbutton', { name: 'Rotation' }).inputValue()).not.toBe(rotationBefore)
  const rotateAfter = await boxCenter(rotateHandle)
  expect(Math.hypot(rotateAfter.x - rotateBefore.x, rotateAfter.y - rotateBefore.y)).toBeGreaterThan(2)

  await page.getByRole('button', { name: 'Duplicate selection' }).click()
  await expect(page.getByRole('treeitem', { name: /Uncountable, Yet Zero Length copy/ })).toBeVisible()
  await page.keyboard.press('Delete')
  await expect(page.getByRole('treeitem', { name: /Uncountable, Yet Zero Length copy/ })).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('treeitem', { name: /Uncountable, Yet Zero Length copy/ })).toBeVisible()
  await page.keyboard.press('Control+Shift+z')

  await page.getByRole('tab', { name: 'Text' }).click()
  await page.getByRole('button', { name: 'Add text' }).click()
  await page.getByRole('tab', { name: 'Math' }).click()
  await page.getByRole('button', { name: 'Add math' }).click()
  await page.getByRole('button', { name: 'Add brace' }).click()
  await page.getByRole('tab', { name: 'Shapes' }).click()
  await page.getByRole('button', { name: 'Insert Circle' }).click()
  await page.getByRole('button', { name: 'Insert Arrow' }).click()
  await page.getByRole('tab', { name: 'Graphs' }).click()
  await page.getByRole('button', { name: 'Add coordinate axes' }).click()
  await page.getByRole('button', { name: 'Add function graph' }).click()
  await expect(page.getByRole('treeitem', { name: /Plain text/ })).toBeVisible()
  await expect(page.getByRole('treeitem', { name: /Mathematical text/ })).toBeVisible()

  const insertedGraph = page.locator('[data-object-type="graph"]').last()
  await expect(insertedGraph).toBeVisible()
  const graphExpression = page.getByRole('textbox', { name: 'Graph expression' })
  await expect(graphExpression).toHaveValue('(x ^ 2)')
  await graphExpression.fill('1 / 0')
  await expect(page.locator('.pc-graph-properties [role="alert"]')).toContainText(/division by zero/i)
  await expect(page.getByRole('button', { name: 'Apply graph draft' })).toBeDisabled()
  await page.getByRole('button', { name: 'Discard graph draft' }).click()
  await expect(graphExpression).toHaveValue('(x ^ 2)')

  let longGraphTerms = Array.from({ length: 32 }, (_, index) => String(-(0.123456789012345 + index * Number.EPSILON)))
  while (longGraphTerms.length > 1) {
    const next: string[] = []
    for (let index = 0; index < longGraphTerms.length; index += 2) next.push(`(${longGraphTerms[index]} + ${longGraphTerms[index + 1]})`)
    longGraphTerms = next
  }
  const longGraphExpression = longGraphTerms[0]
  expect(longGraphExpression.length).toBeGreaterThan(512)
  const longGraphHistory = await historyCount(page)
  await graphExpression.fill(longGraphExpression)
  await page.getByRole('button', { name: 'Apply graph draft' }).click()
  expect(await historyCount(page)).toBe(longGraphHistory + 1)
  await expect(graphExpression).toHaveValue(longGraphExpression)

  const reciprocalHistory = await historyCount(page)
  await graphExpression.fill('1 / x')
  await page.getByRole('button', { name: 'Apply graph draft' }).click()
  expect(await historyCount(page)).toBe(reciprocalHistory + 1)
  const graphGeometry = insertedGraph.locator('[data-graph-status="valid"]')
  await expect(graphGeometry).toHaveAttribute('data-graph-segment-count', '2')
  await expect(graphGeometry).toHaveAttribute('data-graph-diagnostic-codes', 'GRAPH_DISCONTINUITIES_SEGMENTED')
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(graphExpression).toHaveValue(longGraphExpression)
  await page.getByRole('button', { name: 'Redo' }).click()
  await expect(graphExpression).toHaveValue('(1 / x)')

  const insertedArrow = page.locator('[data-object-type="arrow"]').last()
  await expect(insertedArrow).toHaveAttribute('opacity', '1')
  const arrowHitPoint = await insertedArrow.evaluate((element: SVGGraphicsElement) => {
    const point = element.ownerSVGElement!.createSVGPoint()
    point.x = 0
    point.y = 6
    const screenPoint = point.matrixTransform(element.getScreenCTM()!)
    return { x: screenPoint.x, y: screenPoint.y }
  })
  await page.mouse.click(arrowHitPoint.x, arrowHitPoint.y)
  const insertedArrowId = await insertedArrow.getAttribute('data-object-id')
  expect(insertedArrowId).not.toBeNull()
  await expect(page.locator(`[data-layer-object-id="${insertedArrowId}"]`)).toHaveAttribute('aria-selected', 'true')

  await page.getByRole('treeitem', { name: /^Plain text/ }).click()
  const contentField = page.getByRole('textbox', { name: 'Content' })
  await contentField.fill('Edited mathematical narration')
  await contentField.blur()
  await expect(page.locator('[data-object-id="object-text"] .pc-canvas-text')).toContainText('Edited mathematical narration')
  const xPosition = page.getByRole('spinbutton', { name: 'X position' })
  await xPosition.fill('520')
  await xPosition.blur()
  await expect(page.getByRole('spinbutton', { name: 'X position' })).toHaveValue('520')

  await page.getByRole('button', { name: 'Add shot' }).click()
  await expect(editor).toHaveAttribute('data-active-shot-id', /shot-scene-3/)
  const componentShotName = page.getByRole('textbox', { name: 'Shot name' })
  await componentShotName.fill('Semantic component study')
  await componentShotName.blur()
  const componentShotTab = page.getByRole('tab', { name: /^Shot \d+, Semantic component study,/ })
  await expect(componentShotTab).toBeVisible()
  await page.getByRole('tab', { name: 'Components' }).click()
  await expect(page.getByRole('tab', { name: 'Components' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Components' }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('tab', { name: 'Graphs' })).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Components' })).toBeFocused()
  const componentLibrary = page.locator('.pc-component-list')
  await expect(componentLibrary).toHaveAttribute('data-semantic-component-count', '12')
  await expect(componentLibrary.locator('[data-component-id]')).toHaveCount(12)
  expect(await componentLibrary.locator('[data-component-id]').evaluateAll((cards) => cards.map((card) => card.getAttribute('data-component-id')))).toEqual([
    'mathematical-title', 'definition-block', 'proposition-statement', 'proof-step-sequence',
    'equation-chain', 'annotated-diagram', 'case-comparison', 'focus-callout', 'marginal-note',
    'recursive-intervals', 'vector-explanation', 'example-abstraction',
  ])
  await page.getByRole('button', { name: 'Insert Callout' }).click()
  await expect(page.locator('[data-layer-object-id="group-focus-callout"]')).toBeVisible()
  await setSelectedPosition(page, 240, 390)
  const componentDragHistory = await historyCount(page)
  const componentTransfer = await page.evaluateHandle(() => new DataTransfer())
  await page.getByRole('button', { name: 'Insert Vector explanation' }).dispatchEvent('dragstart', { dataTransfer: componentTransfer })
  const componentDropStage = page.locator('.pc-stage')
  const componentDropBounds = await componentDropStage.boundingBox()
  expect(componentDropBounds).not.toBeNull()
  const componentDropPoint = {
    x: componentDropBounds!.x + componentDropBounds!.width * 0.7,
    y: componentDropBounds!.y + componentDropBounds!.height * 0.62,
  }
  await componentDropStage.dispatchEvent('dragover', { dataTransfer: componentTransfer, clientX: componentDropPoint.x, clientY: componentDropPoint.y })
  await componentDropStage.dispatchEvent('drop', { dataTransfer: componentTransfer, clientX: componentDropPoint.x, clientY: componentDropPoint.y })
  await page.getByRole('button', { name: 'Insert Vector explanation' }).dispatchEvent('dragend', { dataTransfer: componentTransfer })
  expect(await historyCount(page)).toBe(componentDragHistory + 1)
  await expect(page.locator('[data-layer-object-id="group-vector-explanation"]')).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('button', { name: 'Insert Title & subtitle' }).click()
  const insertedTitleGroupLayer = page.locator('[data-layer-object-id="group-mathematical-title"]')
  await insertedTitleGroupLayer.click()
  const insertedTitleGroup = page.locator('[data-group-move-target="group-mathematical-title"]')
  await expect(insertedTitleGroup).toBeVisible()
  await setSelectedPosition(page, 480, 110)
  await page.screenshot({ path: path.join(evidenceDir, screenshotName), fullPage: false })
  await setSelectedPosition(page, 480, 230)
  let groupCenterBefore = await boxCenter(insertedTitleGroup)
  const canvasCenter = await page.locator('.pc-stage').evaluate((element: SVGSVGElement) => {
    const point = element.createSVGPoint()
    point.x = 480
    point.y = 270
    const screenPoint = point.matrixTransform(element.getScreenCTM()!)
    return { x: screenPoint.x, y: screenPoint.y }
  })
  await page.mouse.move(groupCenterBefore.x, groupCenterBefore.y)
  await page.mouse.down()
  await page.mouse.move(canvasCenter.x + 3, groupCenterBefore.y, { steps: 5 })
  const xSnapGuide = page.locator('.pc-snap-guide[data-guide-axis="x"]')
  await expect(xSnapGuide).toHaveCount(1)
  await expect(xSnapGuide).toHaveAttribute('x1', '480')
  await page.mouse.up()
  await expect(xSnapGuide).toHaveCount(0)
  groupCenterBefore = await boxCenter(insertedTitleGroup)
  expect(Math.abs(groupCenterBefore.x - canvasCenter.x)).toBeLessThan(2)
  const groupResizeHandle = page.getByLabel(/^Resize selected object;/)
  const groupHistoryBeforeResize = await historyCount(page)
  const groupResizeBefore = await boxCenter(groupResizeHandle)
  await dragBy(page, groupResizeHandle, 30, 15)
  const groupResizeAfter = await boxCenter(groupResizeHandle)
  const groupCenterAfterResize = await boxCenter(insertedTitleGroup)
  expect(Math.abs(groupCenterAfterResize.x - groupCenterBefore.x)).toBeLessThan(2)
  expect(Math.abs(groupCenterAfterResize.y - groupCenterBefore.y)).toBeLessThan(2)
  expect(Math.abs((groupResizeAfter.x - groupResizeBefore.x) - 30)).toBeLessThan(2)
  expect(Math.abs((groupResizeAfter.y - groupResizeBefore.y) - 15)).toBeLessThan(2)
  const groupRotationBefore = await page.getByRole('spinbutton', { name: 'Rotation' }).inputValue()
  await dragBy(page, page.getByLabel(/^Rotate selected object;/), 28, -6)
  expect(await historyCount(page)).toBe(groupHistoryBeforeResize + 2)
  expect(await page.getByRole('spinbutton', { name: 'Rotation' }).inputValue()).not.toBe(groupRotationBefore)
  const groupCenterAfterRotate = await boxCenter(insertedTitleGroup)
  expect(Math.abs(groupCenterAfterRotate.x - groupCenterBefore.x)).toBeLessThan(2)
  expect(Math.abs(groupCenterAfterRotate.y - groupCenterBefore.y)).toBeLessThan(2)
  await insertedTitleGroupLayer.click()
  const insertedVectorGroupLayer = page.locator('[data-layer-object-id="group-vector-explanation"]')
  await insertedVectorGroupLayer.click({ modifiers: ['Shift'] })
  await page.getByRole('button', { name: 'Align right' }).click()
  await insertedTitleGroupLayer.click()
  const alignedGroup = await insertedTitleGroup.boundingBox()
  await insertedVectorGroupLayer.click()
  const alignedTitle = await page.locator('[data-group-move-target="group-vector-explanation"]').boundingBox()
  expect(alignedGroup).not.toBeNull()
  expect(alignedTitle).not.toBeNull()
  expect(Math.abs((alignedGroup!.x + alignedGroup!.width) - (alignedTitle!.x + alignedTitle!.width))).toBeLessThan(2)
  await constructionTab.click()
  await expect(editor).toHaveAttribute('data-active-shot-id', 'shot-cantor-construction')
  await playhead.fill('12.5')
  await page.getByRole('tab', { name: 'Text' }).click()

  const titleLayer = page.getByRole('treeitem', { name: /Uncountable, Yet Zero Length/ })
  const subtitleLayer = page.getByRole('treeitem', { name: /A quiet paradox/ })
  const marginLayer = page.getByRole('treeitem', { name: /Measure note/ })
  await titleLayer.click()
  await subtitleLayer.click({ modifiers: ['Shift'] })
  await marginLayer.click({ modifiers: ['Shift'] })
  before = await historyCount(page)
  await page.getByRole('button', { name: 'Align top' }).click()
  await page.getByRole('button', { name: 'Distribute horizontally' }).click()
  expect(await historyCount(page)).toBe(before + 2)
  const dynamicAxe = await new AxeBuilder({ page }).setLegacyMode(true).analyze()
  const dynamicMaterialA11y = dynamicAxe.violations.filter(({ impact }) => impact === 'critical' || impact === 'serious')
  expect(dynamicMaterialA11y, JSON.stringify(dynamicMaterialA11y, null, 2)).toEqual([])

  await titleLayer.click()
  await subtitleLayer.click({ modifiers: ['Shift'] })
  before = await historyCount(page)
  await page.getByRole('button', { name: 'Group selection', exact: true }).click()
  expect(await historyCount(page)).toBe(before + 1)
  const groupedLayerIds = await page.locator('[data-layer-object-id]').evaluateAll((elements) => elements.map((element) => element.getAttribute('data-layer-object-id')))
  const groupedParentIndex = groupedLayerIds.indexOf('group-selection')
  expect(groupedParentIndex).toBeGreaterThanOrEqual(0)
  expect(groupedLayerIds.slice(groupedParentIndex + 1, groupedParentIndex + 3).sort()).toEqual(['object-subtitle', 'object-title'])
  const groupMoveTarget = page.locator('[data-group-move-target="group-selection"]')
  await expect(groupMoveTarget).toBeVisible()
  await dragBy(page, groupMoveTarget, 18, 10)
  expect(await historyCount(page)).toBe(before + 2)
  await page.getByRole('button', { name: 'Ungroup selection' }).click()
  expect(await historyCount(page)).toBe(before + 3)

  await titleLayer.click()
  await page.getByRole('checkbox', { name: 'Locked' }).check()
  before = await historyCount(page)
  await dragBy(page, title, 24, 0)
  expect(await historyCount(page)).toBe(before)
  await expect(page.getByRole('status', { name: 'Editor status', exact: true })).toContainText('Locked objects')
  await page.getByRole('checkbox', { name: 'Locked' }).uncheck()
  await page.getByRole('button', { name: 'Bring to front' }).click()

  await page.locator(`[data-layer-object-id="${insertedArrowId}"]`).click()
  const blocksBefore = await page.locator('[data-animation-id]').count()
  await page.getByRole('combobox', { name: 'Animation type' }).selectOption('appear')
  await page.getByRole('button', { name: 'Add animation' }).click()
  const newBlock = page.locator('[data-animation-type="appear"]').last()
  await expect(newBlock).toBeVisible()
  await expect(newBlock).toHaveAttribute('data-locked', 'false')
  expect(await page.locator('[data-animation-id]').count()).toBe(blocksBefore + 1)
  const oldStart = await newBlock.getAttribute('data-start')
  // Start in the block body, away from the dedicated right-edge resize grip.
  await dragBy(page, newBlock, 45, 0, 4)
  expect(await newBlock.getAttribute('data-start')).not.toBe(oldStart)
  const oldDuration = await newBlock.getAttribute('data-duration')
  await dragBy(page, page.locator('.pc-animation-block i').last(), 35, 0)
  expect(await newBlock.getAttribute('data-duration')).not.toBe(oldDuration)
  const cameraBlock = page.locator('[data-animation-id="animation-camera-focus"]')
  expect(await cameraBlock.getAttribute('data-timeline-lane')).not.toBe(await newBlock.getAttribute('data-timeline-lane'))
  await cameraBlock.click()
  const cameraZoom = page.getByRole('spinbutton', { name: 'Camera zoom' })
  await cameraZoom.fill('1.18')
  await cameraZoom.blur()
  await expect(page.getByRole('spinbutton', { name: 'Camera zoom' })).toHaveValue('1.18')
  await playhead.fill('6.4')
  await expect(page.locator('[data-object-id="object-generation-note"]')).toHaveCount(0)
  await playhead.fill('6.8')
  await expect(page.locator('[data-object-id="object-generation-note"]')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Scene canvas' })).toHaveAttribute('data-preview-time', '6.8')

  await page.getByRole('button', { name: 'Open command palette' }).click()
  await page.getByRole('option', { name: /AI structured edit/ }).click()
  for (let index = 1; index <= 5; index += 1) {
    await page.getByRole('button', { name: new RegExp(`^Run AI preset ${index}:`) }).click()
    const proposal = page.getByRole('region', { name: 'Proposed changes' })
    await expect(proposal).toBeVisible()
    if (index === 1) {
      await expect(page.getByRole('region', { name: 'AI command' })).toHaveAttribute('data-ai-provider', 'deterministic-demo')
      await expect(page.getByText('Deterministic demo interpreter — limited commands')).toBeVisible()
    }
    await expect(proposal.getByRole('listitem').first()).toBeVisible()
    const transactionBefore = await historyCount(page)
    const visibleBefore = index === 1 ? await title.getAttribute('transform') : null
    await proposal.getByRole('button', { name: 'Apply proposed changes' }).click()
    expect(await historyCount(page)).toBe(transactionBefore + 1)
    const visibleApplied = index === 1 ? await title.getAttribute('transform') : null
    await page.getByRole('button', { name: 'Undo' }).click()
    expect(await historyCount(page)).toBe(transactionBefore)
    if (index === 1) {
      expect(await title.getAttribute('transform')).toBe(visibleBefore)
      await page.getByRole('button', { name: 'Redo' }).click()
      expect(await historyCount(page)).toBe(transactionBefore + 1)
      expect(await title.getAttribute('transform')).toBe(visibleApplied)
      await page.getByRole('button', { name: 'Undo' }).click()
      expect(await historyCount(page)).toBe(transactionBefore)
      expect(await title.getAttribute('transform')).toBe(visibleBefore)
    }
  }
  await page.getByRole('button', { name: 'Close AI command drawer' }).click()

  await titleLayer.click()
  const nameField = page.getByRole('textbox', { name: 'Name', exact: true })
  await nameField.fill('Persisted theorem title')
  await nameField.blur()
  const savedAnimationCount = await page.locator('[data-animation-id]').count()
  await page.getByRole('radio', { name: 'Raw Manim' }).check()
  await page.getByLabel('Owner menu').click()
  await page.getByRole('button', { name: 'Save project' }).click()
  await expect(page.getByRole('status', { name: 'Autosave status' })).toHaveAttribute('data-save-state', 'saved')
  const savedRevision = Number(await editor.getAttribute('data-server-revision'))
  expect(savedRevision).toBeGreaterThan(1)
  await page.reload()
  await expect(editor).toHaveAttribute('data-project-id', projectId!)
  await expect(editor).toHaveAttribute('data-durable', 'true')
  await expect(editor).toHaveAttribute('data-save-state', 'saved')
  await expect(page.getByRole('treeitem', { name: /Persisted theorem title/ })).toHaveAttribute('data-layer-object-id', 'object-title')
  await page.getByRole('tab', { name: /^Shot \d+, Semantic component study,/ }).click()
  await expect(page.locator('[data-layer-object-id="group-focus-callout"]')).toBeVisible()
  await expect(page.locator('[data-layer-object-id="group-vector-explanation"]')).toBeVisible()
  await constructionTab.click()
  await expect(page.getByRole('radio', { name: 'Raw Manim' })).toBeChecked()
  expect(await page.locator('[data-animation-id]').count()).toBe(savedAnimationCount)
  await page.getByRole('radio', { name: 'Editorial Ink' }).check()

  await page.getByRole('button', { name: 'Add shot' }).click()
  await expect(editor).toHaveAttribute('data-active-shot-id', /shot-scene-4/)
  const shotName = page.getByRole('textbox', { name: 'Shot name' })
  await shotName.fill('Closing annotation')
  await shotName.blur()
  const shotDuration = page.getByRole('spinbutton', { name: 'Shot duration' })
  await shotDuration.fill('2.5')
  await shotDuration.blur()
  await page.getByRole('button', { name: 'Move shot later' }).click()
  await expect(page.getByRole('tab', { name: /^Shot \d+, Closing annotation,/ })).toBeVisible()
  await page.getByRole('tab', { name: /^Shot \d+, The construction,/ }).click()
  await expect(editor).toHaveAttribute('data-active-shot-id', 'shot-cantor-construction')

  await page.getByRole('button', { name: 'Render or export' }).click()
  const jsonDownloadPromise = page.waitForEvent('download')
  const exportJsonButton = page.getByRole('button', { name: 'Export project JSON' })
  await exportJsonButton.click()
  const jsonDownload = await jsonDownloadPromise
  const jsonPath = await jsonDownload.path()
  expect(jsonPath).not.toBeNull()
  const exportedJson = await readFile(jsonPath!, 'utf8')
  const exportedProject = JSON.parse(exportedJson)
  expect(exportedProject.metadata.id).toBe(projectId)
  expect(exportedProject.activeStyleId).toBe('style-editorial-ink')
  expect(exportedProject.shots[0].objects.some((object: { type: string }) => object.type === 'group')).toBe(true)
  expect(exportedProject.shots[0].animations.length).toBeGreaterThan(0)
  const closeJsonPreview = page.getByRole('button', { name: 'Close export preview' })
  await expect(closeJsonPreview).toBeFocused()
  expect(await page.locator('.pc-header').evaluate((element: HTMLElement) => element.inert)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Project JSON' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Render or export' })).toBeFocused()

  await page.getByRole('button', { name: 'Render or export' }).click()
  const pythonDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Manim Python' }).click()
  const pythonDownload = await pythonDownloadPromise
  const pythonPath = await pythonDownload.path()
  expect(pythonPath).not.toBeNull()
  expect(await readFile(pythonPath!, 'utf8')).toContain('class GeneratedScene(MovingCameraScene):')
  await page.getByRole('button', { name: 'Close export preview' }).click()

  await page.getByLabel('Owner menu').click()
  const importInput = page.getByLabel('Import project JSON')
  await importInput.focus()
  expect(await importInput.locator('..').evaluate((element) => element.matches(':focus-within'))).toBe(true)
  await importInput.setInputFiles({ name: 'project.json', mimeType: 'application/json', buffer: Buffer.from(exportedJson) })
  await expect(editor).toHaveAttribute('data-project-id', projectId!)
  await page.getByRole('tab', { name: /^Shot \d+, Semantic component study,/ }).click()
  await expect(page.locator('[data-layer-object-id="group-focus-callout"]')).toBeVisible()
  await constructionTab.click()
  expect(await page.locator('[data-animation-id]').count()).toBe(exportedProject.shots[0].animations.length)
  await page.getByLabel('Owner menu').click()
  await importInput.setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":999}') })
  await expect(page.locator('.pc-message[role="alert"]')).toContainText(/schema version|unsupported|invalid|expected/i)
  await page.getByRole('button', { name: 'Dismiss', exact: true }).click()
  await expect(editor).toHaveAttribute('data-project-id', projectId!)

  await page.getByRole('button', { name: 'Open command palette' }).click()
  await page.getByRole('option', { name: /AI structured edit/ }).click()
  await page.getByRole('button', { name: 'Critique composition' }).click()
  await expect(page.locator('[data-issue-kind]').first()).toBeVisible()
  await page.getByRole('button', { name: 'Close AI command drawer' }).click()

  if (testInfo.project.name === 'proofcanvas-chromium-1440') {
    await page.getByRole('button', { name: 'Render or export' }).click()
    await page.getByRole('button', { name: 'Render MP4' }).click()
    const renderStatus = page.getByRole('region', { name: 'Render status' })
    await expect(renderStatus).toHaveAttribute('data-render-status', 'succeeded', { timeout: 240_000 })
    const video = page.getByLabel('Rendered Manim preview')
    await expect(video).toBeVisible()
    const inspectedVideo = await video.evaluate((node: HTMLVideoElement) => ({
      controls: node.controls,
      preload: node.preload,
      source: node.getAttribute('src'),
      width: node.getBoundingClientRect().width,
    }))
    expect(inspectedVideo).toMatchObject({ controls: true, preload: 'metadata' })
    expect(inspectedVideo.source).toMatch(/^\/api\/proofcanvas\/render\/[A-Za-z0-9_-]{24}\/video$/)
    expect(inspectedVideo.width).toBeGreaterThan(0)

    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('link', { name: 'Download MP4' }).click()
    const download = await downloadPromise
    const downloadDirectory = path.join(evidenceDir, 'ui-download')
    await mkdir(downloadDirectory, { recursive: true })
    const savedVideo = path.join(downloadDirectory, 'proofcanvas-render.mp4')
    await download.saveAs(savedVideo)
    const bytes = await readFile(savedVideo)
    expect(bytes.byteLength).toBeGreaterThan(32)
    expect(bytes.subarray(4, 8).toString('ascii')).toBe('ftyp')
  }

  expect(consoleErrors, consoleErrors.join('\n')).toEqual([])
})
