import { expect, test } from '@playwright/test'

test('reopens the durable portrait project after a controlled application process restart', async ({ page }) => {
  const ownerPassword = process.env.PROOFCANVAS_E2E_OWNER_PASSWORD
  expect(ownerPassword, 'The restart journey must retain the ephemeral owner password').toBeTruthy()
  const consoleErrors: string[] = []
  const networkErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  page.on('requestfailed', (request) => {
    networkErrors.push(`${request.method()} ${request.url()} failed: ${request.failure()?.errorText ?? 'unknown error'}`)
  })
  page.on('response', (response) => {
    if (response.status() >= 500) networkErrors.push(`${response.request().method()} ${response.url()} returned ${response.status()}`)
  })

  await page.goto('/login')
  await page.getByLabel('Owner password').fill(ownerPassword!)
  await page.getByRole('button', { name: 'Log in' }).click()
  await expect(page.getByRole('heading', { name: 'Your mathematical motion projects' })).toBeVisible()
  await page.getByRole('link', { name: 'Open Restart-persisted portrait proof' }).click()
  const editor = page.getByRole('application', { name: 'ProofCanvas editor' })
  await expect(editor).toHaveAttribute('data-durable', 'true')
  await expect(editor).toHaveAttribute('data-save-state', 'saved')
  expect(Number(await editor.getAttribute('data-server-revision'))).toBeGreaterThan(1)
  await expect(editor).toHaveAttribute('data-active-shot-id', 'shot-main')
  await expect(page.getByRole('textbox', { name: 'Project title' })).toHaveValue('Restart-persisted portrait proof')
  await expect(page.getByRole('tab', { name: /^Shot 1, Portrait proof,/ })).toBeVisible()
  const titleLayer = page.getByRole('treeitem', { name: /Portrait title/ })
  const arrowLayer = page.getByRole('treeitem', { name: /Portrait arrow/ })
  await expect(titleLayer).toBeVisible()
  await expect(arrowLayer).toBeVisible()
  const titleId = await titleLayer.getAttribute('data-layer-object-id')
  const arrowId = await arrowLayer.getAttribute('data-layer-object-id')
  expect(titleId).toMatch(/^object-/)
  expect(arrowId).toMatch(/^object-/)
  await expect(page.locator('[data-animation-id]')).toHaveCount(2)
  const write = page.locator('[data-animation-type="write"]')
  const fade = page.locator('[data-animation-type="fade-in"]')
  await expect(write).toHaveAttribute('data-target-ids', titleId!)
  await expect(write).toHaveAttribute('data-start', '0.2')
  await expect(write).toHaveAttribute('data-duration', '0.8')
  await expect(fade).toHaveAttribute('data-target-ids', arrowId!)
  await expect(fade).toHaveAttribute('data-start', '0.5')
  await expect(fade).toHaveAttribute('data-duration', '0.8')

  await titleLayer.click()
  await expect(page.getByRole('textbox', { name: 'Content' })).toHaveValue('A portrait proof, authored by hand')
  await expect(page.getByRole('spinbutton', { name: 'X position' })).toHaveValue('270')
  await expect(page.getByRole('spinbutton', { name: 'Y position' })).toHaveValue('360')
  await expect(page.getByRole('spinbutton', { name: 'Width', exact: true })).toHaveValue('440')
  await arrowLayer.click()
  await expect(page.getByRole('spinbutton', { name: 'X position' })).toHaveValue('270')
  await expect(page.getByRole('spinbutton', { name: 'Y position' })).toHaveValue('540')
  await page.getByRole('button', { name: 'Project settings' }).click()
  await expect(page.getByRole('combobox', { name: 'Aspect ratio' })).toHaveValue('9:16')
  await expect(page.getByRole('combobox', { name: 'Frame rate' })).toHaveValue('24')
  await expect(page.getByRole('combobox', { name: 'Render preset' })).toHaveValue('draft')
  await page.getByRole('button', { name: 'Close project settings' }).click()
  await page.getByRole('tab', { name: 'Media' }).click()
  const persistedAudioAssets = page.locator('.pc-audio-assets article')
  await expect(persistedAudioAssets).toHaveCount(1, { timeout: 30_000 })
  await expect(page.locator('.pc-media-library [data-available="false"]')).toHaveCount(0)
  await expect(persistedAudioAssets.first()).toHaveAttribute('data-available', 'true')
  await expect(persistedAudioAssets.first()).toContainText('proofcanvas-deterministic-pulse-90s.wav')
  await expect(persistedAudioAssets.first().locator('.pc-waveform[data-waveform-state="ready"]')).toBeVisible({ timeout: 30_000 })
  await expect(page.locator('.pc-audio-clip')).toHaveCount(0)
  await page.getByRole('slider', { name: 'Sequence time' }).fill('1.5')
  const stage = page.locator('.pc-stage')
  const stageBounds = await stage.boundingBox()
  expect(stageBounds).not.toBeNull()
  for (const objectId of [titleId!, arrowId!]) {
    const object = page.locator(`[data-object-id="${objectId}"]`)
    await expect(object).toBeVisible()
    const bounds = await object.boundingBox()
    expect(bounds).not.toBeNull()
    expect(bounds!.x).toBeGreaterThanOrEqual(stageBounds!.x - 1)
    expect(bounds!.y).toBeGreaterThanOrEqual(stageBounds!.y - 1)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(stageBounds!.x + stageBounds!.width + 1)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(stageBounds!.y + stageBounds!.height + 1)
  }
  expect(consoleErrors, consoleErrors.join('\n')).toEqual([])
  expect(networkErrors, networkErrors.join('\n')).toEqual([])
})
